### ISSUE TITLE
想使用您的博客主题

### ISSUE THREAD

**Issue by waterhydroxyl** [sfantree/hexo-theme-Amativeness#1]
请问能否开源一下sfantree.com的worldpress主题让我学习使用，由diygod发布的主题或许后期更改出现错误，导致部分功能无法使用

**Comment by sfantree** [comment]
https://github.com/DIYgod/diygod.me

**Comment by waterhydroxyl** [comment]
这个不是hexo的主题吗？我想要wordpress的...
